# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: dev@accushield.com
  email_provider_password: "@ccuSh13ldDev"
  domain_name: accushield-monitor-dev.herokuapp.com
  secret_key_base: d8f6b18e55baddfc80f2e7d2ce5083f182469b7f826e99a63cf83f82634f19f2732332ac8c47c0f3b9cb04be14328527870e112447e9f4f6c4b19df083a674ab

staging:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: dev@accushield.com
  email_provider_password: "@ccuSh13ldDev"
  domain_name: accushield.com
  secret_key_base: d8f6b18e55baddfc80f2e7d2ce5083f182469b7f826e99a63cf83f82634f19f2732332ac8c47c0f3b9cb04be14328527870e112447e9f4f6c4b19df083a674ab

test:
  domain_name: example.com 
  secret_key_base: 2e45027eec3979b75d3c74ba0474bf30dbc492a85a194370c14053378dcf30fd280f87653e42f35955f4d1247f58a86c9214c8d50ec5eeee7ca492dad1341272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: dev@accushield.com
  email_provider_password: "@ccuSh13ldDev"
  domain_name: monitor.accushield.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>