# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user = CreateAdminService.new.call

UsState.create(code:"AL",name:"Alabama")
UsState.create(code:"AK",name:"Alaska")
UsState.create(code:"AS",name:"American Samoa")
UsState.create(code:"AZ",name:"Arizona")
UsState.create(code:"AR",name:"Arkansas")
UsState.create(code:"AE",name:"Armed Forces Africa")
UsState.create(code:"AA",name:"Armed Forces Americas")
UsState.create(code:"AE",name:"Armed Forces Canada")
UsState.create(code:"AE",name:"Armed Forces Europe")
UsState.create(code:"AE",name:"Armed Forces Middle East")
UsState.create(code:"AP",name:"Armed Forces Pacific")
UsState.create(code:"CA",name:"California")
UsState.create(code:"CC",name:"Canada")
UsState.create(code:"CO",name:"Colorado")
UsState.create(code:"CT",name:"Connecticut")
UsState.create(code:"DE",name:"Delaware")
UsState.create(code:"XX",name:"Deleted")
UsState.create(code:"DC",name:"District of Columbia")
UsState.create(code:"FM",name:"Federated States of Micronesia")
UsState.create(code:"FL",name:"Florida")
UsState.create(code:"GA",name:"Georgia")
UsState.create(code:"GU",name:"Guam")
UsState.create(code:"HI",name:"Hawaii")
UsState.create(code:"ID",name:"Idaho")
UsState.create(code:"IL",name:"Illinois")
UsState.create(code:"IN",name:"Indiana")
UsState.create(code:"IA",name:"Iowa")
UsState.create(code:"KS",name:"Kansas")
UsState.create(code:"KY",name:"Kentucky")
UsState.create(code:"LA",name:"Louisiana")
UsState.create(code:"ME",name:"Maine")
UsState.create(code:"MH",name:"Marshall Islands")
UsState.create(code:"MD",name:"Maryland")
UsState.create(code:"MA",name:"Massachusetts")
UsState.create(code:"MI",name:"Michigan")
UsState.create(code:"MN",name:"Minnesota")
UsState.create(code:"MS",name:"Mississippi")
UsState.create(code:"MO",name:"Missouri")
UsState.create(code:"MT",name:"Montana")
UsState.create(code:"NE",name:"Nebraska")
UsState.create(code:"NV",name:"Nevada")
UsState.create(code:"NH",name:"New Hampshire")
UsState.create(code:"NJ",name:"New Jersey")
UsState.create(code:"NM",name:"New Mexico")
UsState.create(code:"NY",name:"New York")
UsState.create(code:"NC",name:"North Carolina")
UsState.create(code:"ND",name:"North Dakota")
UsState.create(code:"MP",name:"Northern Mariana Islands")
UsState.create(code:"OH",name:"Ohio")
UsState.create(code:"OK",name:"Oklahoma")
UsState.create(code:"OR",name:"Oregon")
UsState.create(code:"PW",name:"Palau")
UsState.create(code:"PA",name:"Pennsylvania")
UsState.create(code:"PR",name:"Puerto Rico")
UsState.create(code:"RI",name:"Rhode Island")
UsState.create(code:"SC",name:"South Carolina")
UsState.create(code:"SD",name:"South Dakota")
UsState.create(code:"TN",name:"Tennessee")
UsState.create(code:"TX",name:"Texas")
UsState.create(code:"UT",name:"Utah")
UsState.create(code:"VT",name:"Vermont")
UsState.create(code:"VI",name:"Virgin Islands")
UsState.create(code:"VA",name:"Virginia")
UsState.create(code:"WA",name:"Washington")
UsState.create(code:"WV",name:"West Virginia")
UsState.create(code:"WI",name:"Wisconsin")
UsState.create(code:"WY",name:"Wyoming")
